version: '3'

services:
    customer-portrait:
        image: your_image_name:${TAG}
        volumes:
            - ${PATH}:/app/data
        ports:
            - "8501:8501"

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app