name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    -
      name: Get latest git tag
      run: echo "LATEST_TAG=streamlit-$(git describe --tags --abbrev=7)" >> $GITHUB_ENV

    -
      name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t runtime:${{ env.LATEST_TAG }} .
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker tag runtime:${{ env.LATEST_TAG }} ${{ secrets.DEPOSITORY }}/etude-client-runtime:${{ env.LATEST_TAG }}
        docker push ${{ secrets.DEPOSITORY }}/etude-client-runtime:${{ env.LATEST_TAG }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    -
      name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    -
      name: Get latest git tag
      run: echo "LATEST_TAG=streamlit-$(git describe --tags --abbrev=7)" >> $GITHUB_ENV

    -
      name: Connect to VPN
      run: |
        sudo apt-get update
        sudo apt-get install openconnect network-manager-openconnect network-manager-openconnect-gnome
        echo "${{ secrets.VPN_PWD }}" | sudo openconnect -u ${{ secrets.VPN_USER }} --passwd-on-stdin --protocol=fortinet ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --servercert ${{ secrets.VPN_SERVERCERT }} &
    -
      name: Deploy on Data PC
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PC_HOST }}
        username: ${{ secrets.PC_USER }}
        password: ${{ secrets.PC_PASSWORD }}
        script: |
          powershell -ExecutionPolicy Bypass -File ${{ secrets.PC_PATH }}docker-cleanup.ps1 ${{ secrets.PC_PATH }} ${{ secrets.DEPOSITORY }} ${{ env.LATEST_TAG }} ${{ secrets.PC_DATA_PATH }} ${{ secrets.ENV_PATH}} ${{ secrets.DATA_USERNAME}} ${{ secrets.DATA_PASSWORD}} ${{ secrets.MARKETING_USERNAME}} ${{ secrets.MARKETING_PASSWORD}}
